### ISSUE TITLE
Zoom in on stream

### ISSUE THREAD

**Issue by Jorson-Lee** [tsoding/faq#30]
Hi Tsoding, I want to ask how do you zoom in the screen when you enmphasizing something on yt videos / streams?
Is that an OBS plug-in or application on the computer?
Thank you😊

**Comment by asedmammad** [comment]
I think he uses [https://github.com/tsoding/boomer](https://github.com/tsoding/boomer) which is a zoom application for Linux.

**Comment by Jorson-Lee** [comment]
> I think he uses https://github.com/tsoding/boomer which is a zoom application for Linux.

Thank you very much😊
